name: CI/CD workflow for Maven Build and Sonar Code scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2.0.0
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=my-Java-web-app
          # Se você usa SonarCloud e precisa da organização, descomente a linha abaixo:
          # -Dsonar.organization=my-org
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
